on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: codeberg-tiny
    steps:
      - uses: https://github.com/actions/checkout@v4
      - uses: https://github.com/actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: npx wrangler pages deploy dist --project-name studyinc-frontend
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}